gnb_id: 512
gnb_id_bit_length: 22
gnb_du_id: 3003


f1ap:
  cu_cp_addr: 175.53.1.12               # The address of CU-CP
  bind_addr: 175.53.1.14

f1u:
  socket:
    -
      bind_addr: 175.53.1.14

ru_sdr:
  #device_driver: uhd
  device_driver: zmq
  #device_args: type=b200,num_recv_frames=64,num_send_frames=64
  device_args: tx_port0=tcp://175.53.1.14:20010,rx_port0=tcp://175.53.4.1:20011,tx_port1=tcp://175.53.1.14:20020,rx_port1=tcp://175.53.4.2:20021, tx_port2=tcp://175.53.1.14:20030,rx_port2=tcp://175.53.4.3:20031,base_srate=23.04e6 # Optionally pass arguments to the selected RF driver.
  srate: 23.04
  #otw_format: sc12
  tx_gain: 50
  rx_gain: 40

cell_cfg:
  dl_arfcn: 368500
  sector_id: 2
  band: 3
  channel_bandwidth_MHz: 20
  common_scs: 15
  plmn: "00101"
  tac: 7
  pci: 3

  pdcch:
    common:
      ss0_index: 0                  # Set search space zero index to match srsUE capabilities
      coreset0_index: 12            # Set search CORESET Zero index to match srsUE capabilities
    dedicated:
      ss2_type: common              # Search Space type, has to be set to common
      dci_format_0_1_and_1_1: false # Set correct DCI format (fallback)
  prach:
    prach_config_index: 1           # Sets PRACH config to match what is expected by srsUE
  pdsch:
    mcs_table: qam64                # Sets PDSCH MCS to 64 QAM
  pusch:
    mcs_table: qam64                # Sets PUSCH MCS to 64 QAM


metrics: 
  addr: 175.40.1.4                        # Optional TEXT:IPV4 (127.0.0.1). Sets the metrics address. Supported: IPV4 address.
  enable_json: true
  port: 55555                           # Optional UINT. Sets the metrics UPD port. Supported: [0 - 65535].
  layers: 
    enable_app_usage: true
    enable_sched: true
    enable_rlc: true
    enable_mac: true
    enable_executor: true
    enable_du_low: true
    enable_ru: true
  periodicity:
    app_usage_report_period: 500
    du_report_period: 500
